activities/urls.py
from django.urls import path

from .import views

app_name = 'activities'

urlpatterns = [
    path('', views.activities, name='activities'),
    path('post-kegiatan',views.post_kegiatan),
    path('post-peserta/<int:id_kegiatan>',views.post_peserta),
]

main/urls.py
from django.urls import path,include

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signin/', views.signup, name="signup"),
]

project/urls.py
from django.urls import path

from . import views

app_name = 'project'

urlpatterns = [
    path('', views.project, name='project'),
]

schedule/urls.py
from django.urls import path

from . import views

app_name = 'schedule'

urlpatterns = [
    path('', views.schedule, name='schedule'),
    path('add/', views.add, name='addschedule'),
    path('delete/<str:pk>/',views.delete, name='delete'),
]

search/urls.py
from django.urls import path

from . import views

app_name = 'search'

urlpatterns = [
    path('', views.search, name='search'),
]

story_4/urls.py
from django.contrib import admin
from django.urls import include, path
from search.views import caridata
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('activities/', include('activities.urls')),
    path('project/',include('project.urls')),
    path('schedule/',include('schedule.urls')),
    path('search/',include('search.urls')),
    path('data/',caridata)



]

activities/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    nama = models.CharField(max_length = 30)

    def __str__(self):
        return self.nama

class Peserta(models.Model):
    nama = models.CharField(max_length = 30)
    kegiatan = models.ForeignKey(Kegiatan,on_delete = models.DO_NOTHING)

    def __str__(self):
        return self.nama
 

main/models.py
from django.db import models

# Create your models here.

project/models.py
from django.db import models

# Create your models here.

schedule/models.py
from django.db import models

# Create your models here.
class Matkul(models.Model):
    nama_matkul = models.CharField(max_length=50)
    semester_tahun = models.CharField(max_length=20)
    jumlah_sks = models.CharField(max_length=10, default=0)
    nama_dosen = models.CharField(max_length=50)
    ruang_kuliah = models.CharField(max_length=50)
    deskripsi = models.CharField(max_length=100)

search/models.py
from django.db import models

# Create your models here.

activities/forms.py
from django.forms.models import ModelForm
from .models import Peserta,Kegiatan
from django import forms

class KegiatanForm(forms.Form):
    nama_kegiatan = forms.CharField(label="Nama Kegiatan", max_length=64,
    widget=forms.TextInput(attrs={'class': 'form-control'}))

class PesertaForm(forms.Form):
    nama_peserta = forms.CharField(label="Ikuti acara", max_length=64,
    widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'Masukan Nama'}))

main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class SignUpForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    email=forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}), max_length=64, help_text='Enter a valid email address')
    password1=forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Input Password'}))
    password2=forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Input Password Again'}))
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(),
            'password2': forms.PasswordInput(),
        }

activities/views.py
from django.shortcuts import render,redirect
from .forms import KegiatanForm,PesertaForm
from .models import Kegiatan,Peserta

# Create your views here.
def activities(request):
    data ={
        'kegiatan':Kegiatan.objects.all(),
        'peserta':Peserta.objects.all(),
    }
    form_data ={
        'form_kegiatan':KegiatanForm,
        'form_peserta': PesertaForm,
    }
    content = {
        'nbar':'activities',
        'forms':form_data,
        'database':data
        }
    return render(request, 'activities/act.html', content)

def post_kegiatan(request):
    if request.method == 'POST':
        form = KegiatanForm(request.POST or None)
        if form.is_valid():
            data_form = form.cleaned_data
            data = Kegiatan(nama=data_form['nama_kegiatan'])
            data.save()
            return redirect('/activities/')
        else:
            return redirect('/activities/')
    else:
        return redirect('/activities/')
    
def post_peserta(request, id_kegiatan):
    if request.method == 'POST':
        form = PesertaForm(request.POST or None)
        if form.is_valid():
            kegiatan = Kegiatan.objects.get(id=id_kegiatan)
            data_form = form.cleaned_data
            data_input = Peserta()
            data_input.nama = data_form['nama_peserta']
            data_input.kegiatan = kegiatan

            data_input.save()
            return redirect('/activities/')
        else:
            return redirect('/activities/')
    else:
        return redirect('/activities/')

main/views.py
from django.shortcuts import render
from django.contrib.auth import login, authenticate
from .forms import SignUpForm
from django.shortcuts import render, redirect

def home(request):
    return render(request, 'main/home.html',{'nbar':'home'})

def signup(request):
    form = SignUpForm(request.POST)
    if form.is_valid():
        form.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('main:home')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

project/views.py
from django.shortcuts import render

# Create your views here.
def project(request):
    return render(request, 'project/prop.html',{'nbar':'project'})

schedule/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from .models import Matkul

# Create your views here.
def schedule(request): 
    matkuls = Matkul.objects.all()
    context = {
        'object_list': matkuls,
        'nbar':'schedule',
    }
    return render(request, 'schedule/schedule.html',context)

def add(request):
    parameter = False
    nama = ""
    if request.method == "POST":
        parameter = True
        mata = request.POST.get("nama")
        semester = request.POST.get("semester")
        sks = request.POST.get("sks")
        dosen = request.POST.get("dosen")
        ruang = request.POST.get("ruang")
        desk = request.POST.get("desc")
        p = Matkul.objects.create(nama_matkul = mata, semester_tahun = semester, jumlah_sks = sks, nama_dosen = dosen, ruang_kuliah = ruang, deskripsi = desk)
        p.save()
        nama = mata
        return redirect("/schedule")

    context = {
        'par' : parameter,
        'nbar':'schedule',
        'tes': nama,

    }
    return render(request, 'schedule/add.html',context)

def delete(request, pk):
    item=Matkul.objects.get(id=pk)
    if request.method == "POST":
        item.delete()
        return redirect("/schedule")
    context ={
        'nbar':'schedule',
        'matkul': item,
    }
    return render(request,'schedule/delete.html',context)

def savecourse(request):
    return HttpResponseRedirect('/schedule')

search/views.py
from django.shortcuts import render
from django.http import JsonResponse,HttpRequest
import requests
import json
# Create your views here.
def search(request): 
    context = {
        'nbar':'search',
    }
    return render(request, 'search/search.html',context)

def caridata(request):
    arg = request.GET['q']
    url_tujuan = 'https://www.googleapis.com/books/v1/volumes?q=' + arg
    isi = requests.get(url_tujuan)
    data = json.loads(isi.content)
    return JsonResponse(data, safe = False)

activities/templates/activities/act.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Activities</title>
{% endblock meta %} {% block content %}
<div class="container-fluid ">
    <!-- Content here -->
    <div class="head">
        <h1>Activities</h1>
    </div> 
    <div class="container">
        <div class="tengah row">
            {% for kegiatan in database.kegiatan %}
            <div class="content col-3">
                <h3>{{ kegiatan.nama }}</h3>
                {% for peserta in database.peserta %}
                    {% if peserta.kegiatan.nama == kegiatan.nama %}
                    <p>{{ peserta.nama }}</p>
                    {% endif %}
                {% endfor %}
                <div class="pinggir">

                    <hr class ="bg-primary">
                    <form id="form" method="POST" action="/activities/post-peserta/{{ kegiatan.id }}" enctype="multipart/form-data"> 
                    {% csrf_token %}
                        {{ forms.form_peserta.as_p }}

                        <button type="submit" class="btn btn-outline-primary btn-block btn-lg">Submit</button>
                    </form>
                </div>
            </div>
            {% endfor %} 
        </div>
            <button type="button" class="btn btn-primary btn-circle btn-xl float" data-toggle="modal" data-target="#Tambahkegiatan"></button>
            <div class="tulisan modal fade" id="Tambahkegiatan" tabindex="-1" role="dialog" aria-labelledby="tambahkegiatanTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLongTitle">Pendaftaran</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <form id="form" method="POST" action="/activities/post-kegiatan" enctype="multipart/form-data">{% csrf_token %}
                                 {{ forms.form_kegiatan.as_p }}

                                <button type="submit" class="btn btn-primary btn-block btn-lg">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Home</title>
{% endblock meta %} {% block content %}
<div class="container-fluid ">
    <!-- Content here -->

    <div class="row ">
        <div id="carouselme" class="me col-sm carousel slide carousel-fade " data-ride="carousel ">
            <div class="carousel-inner ">
                <div class="carousel-item active ">
                    <img src="{% static '/img/me.jpg' %}" class="tales img-responsive d-block w-100 " alt="... ">
                </div>                  
                <div class="carousel-item ">
                    <img src="{% static '/img/me2.jpg' %}" class="tales d-block w-100 " alt="... ">
                </div> 
                <div class="carousel-item ">
                    <img src="{% static '/img/me3.jpg' %}" class="tales d-block w-100 " alt="... ">
                </div>                 
            </div>
            <a class="carousel-control-prev " href="#carouselme" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon " aria-hidden="true "></span>
                <span class="sr-only ">Previous</span>
            </a>
            <a class="carousel-control-next " href="#carouselme" role="button" data-slide="next">
                <span class="carousel-control-next-icon " aria-hidden="true "></span>
                <span class="sr-only ">Next</span>
            </a>
        </div>
        <div class="judul col-sm ">
            <h4>Hello, I'm</h4>
            <h1 class="name ">Yadhit Prasetya</h1>
            <p class="stat ">Sophomore Student of Information System at University Indonesia</p>
        </div>
    </div>

    

    <div class="row ">

        <div class="judul col-sm ">
            <h1>Education</h1>
        </div>

        <div class="accordion-container col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
            <div class="inikotak" id="satu">
                <div class="kotak kotak-satu">
                    <div class="accordion-head">
                        <h5>Activity</h5>
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <button type="button" class="btn btn-secondary up-button"><img src="{% static '/logo/keyboard_arrow_up-white-18dp.svg' %}"></img></button>
                            <button type="button" class="btn btn-secondary down-button"><img src="{% static '/logo/keyboard_arrow_down-white-18dp.svg' %}"></img></button>
                            <a class="btn btn-primary" id = "activitySatu"><img src="{% static '/logo/dehaze-white-18dp.svg' %}"></a>
                        </div>
                    </div>
                    <div class="accordion-content" id="content-satu">
                        <div class="activity-content column">
                            <h5>Sophomore Student of Fasilkom UI</h5>
                        </div>
                        <div class="activity-content column">
                            <h5>HRD of Communication and Information Bureau at IMAMI UI</h5>
                        </div>
                        <div class="activity-content column">
                            <h5>Deputy of Design Divition of KGTK 18 </h5>
                        </div>
                    </div>
                </div>
            </div>

            <div class="inikotak" id="dua">
                <div class="kotak kotak-dua">
                    <div class="accordion-head">
                        <h5>General Information</h5>
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <button type="button" class="btn btn-secondary up-button"><img src="{% static '/logo/keyboard_arrow_up-white-18dp.svg' %}"></img></button>
                            <button type="button" class="btn btn-secondary down-button"><img src="{% static '/logo/keyboard_arrow_down-white-18dp.svg' %}"></img></button>
                            <a class="btn btn-primary" id = "activityDua"><img src="{% static '/logo/dehaze-white-18dp.svg' %}"></a>
                        </div>
                    </div>
                    <div class="accordion-content" id="content-dua">
                        <table>
                            <tr>
                                <td>Full Name</td>
                                <td>: Yadhit Prasetya</td>
                            </tr>
                            <tr>
                                <td>Nick Name</td>
                                <td>: Yadhit</td>
                            </tr>
                                <td>Date of Birth</td>
                                <td>: 2<sup>nd</sup> June 2000 </td>
                            </tr>
                            <tr>
                                <td>Religion</td>
                                <td>: Islam</td>
                            </tr>
                            <tr>
                                <td>Address</td>
                                <td>: Kota Solok, Sumatera Barat</td>
                            </tr>
                            <tr>
                                <td>Nationality</td>
                                <td>: Indonesia</td>
                            </tr>
                            <tr>
                                <td>Email</td>
                                <td>: yadhitprasetyaixa@gmail.com</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>

            <div class="inikotak" id="tiga">
                <div class="kotak kotak-tiga">
                    <div class="accordion-head">
                        <h5>Skill</h5>
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <button type="button" class="btn btn-secondary up-button"><img src="{% static '/logo/keyboard_arrow_up-white-18dp.svg' %}"></img></button>
                            <button type="button" class="btn btn-secondary down-button"><img src="{% static '/logo/keyboard_arrow_down-white-18dp.svg' %}"></img></button>                     
                            <a class="btn btn-primary" id = "activityTiga"><img src="{% static '/logo/dehaze-white-18dp.svg' %}"></a>
                        </div>
                    </div>
                    <div class="accordion-content" id="content-tiga">
                        <div class="activity-content column">
                            <h5>Basic Programing</h5>
                        </div>
                        <div class="activity-content column">
                            <h5>Graphic Design</h5>
                        </div>
                        <div class="activity-content column">
                            <h5>Video Editing</h5>
                        </div>
                        <div class="activity-content column">
                            <h5>Photography</h5>
                        </div>
                    </div>
                </div>
            </div>

            <div class="inikotak" id="empat">
                <div class="kotak kotak-empat">
                    <div class="accordion-head">
                        <h5>Education</h5>
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <button type="button" class="btn btn-secondary up-button"><img src="{% static '/logo/keyboard_arrow_up-white-18dp.svg' %}"></img></button>
                            <button type="button" class="btn btn-secondary down-button"><img src="{% static '/logo/keyboard_arrow_down-white-18dp.svg' %}"></img></button>         
                            <a class="btn btn-primary" id = "activityEmpat"><img src="{% static '/logo/dehaze-white-18dp.svg' %}"></img></a>
                        </div>
                    </div>
                    <div class="accordion-content" id="content-empat">
                        <div class="education-content">
                                <h5>SDN 01 Tanah Garam</h5>
                                <p>2007 - 2013</p>
                        </div>
                        <div class="education-content">
                                <h5>SMPN 1 Kota Solok</h5>
                                <p>2016 - 2019</p>
                        </div>
                        <div class="education-content">
                                <h5>SMAN 1 Padang Panjang</h5>
                                <p>2016 - 2019</p>
                        </div>
                        <div class="education-content">
                                <h5>Universitas Indonesia</h5>
                                <p>2019 - now</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    
</div>
{% endblock content %}

project/templates/project/prop.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Project</title>
{% endblock meta %} {% block content %}
<div class="container-fluid ">
    <!-- Content here -->

    <div class="container-fluid">
        <div class="halaman">
            <h1>I'm Sorry</h1>
            <h3>Nothing to see here :"</h3>
            <h3>I hope I will get some project to display here soon </h3>
        </div>
    </div>
</div>
{% endblock content %}

schedule/templates/schedule/delete.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>My Schedule</title>
{% endblock meta %} {% block content %}
<div class="container-fluid ">
    <!-- Content here -->

    <div class="container-fluid">

        <div class="halaman">
            <h2>Apakah kamu ingin menghapus {{matkul.nama_matkul}}</h2>

            <form action="." method="POST">{% csrf_token %}
                <a class="btn btn-outline-primary" href="{% url 'schedule:schedule' %}">Cancel</a>
                <input class="btn btn-outline-danger" type="submit" Value="Confirm" name"Confirm">
            </form>
        </div>
        
    </div>
</div>
{% endblock content %}

schedule/templates/schedule/schedule.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>My Schedule</title>
{% endblock meta %} {% block content %}
<div class="container-fluid ">
    <!-- Content here -->

    <div class="container-fluid">
        <div class="halaman">
            <div class="top">
                <a class="nav-link" href="{% url 'schedule:addschedule'%}">
                    <button type="button" class="btn btn-outline-primary" href="{% url 'schedule:addschedule'%}">Add Schedule</button>
                </a>
            </div>

            <div>
                <table class="table table-dark tampilan">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Mata Kuliah</th>
                            <th scope="col">Semester</th>
                            <th scope="col">Jumlah SKS</th>
                            <th scope="col">Nama Dosen</th>
                            <th scope="col">Ruang Kuliah</th>
                            <th scope="col">Deskripsi</th>
                        </tr>
                    </thead>
                    <tbody>
                            {% for matkul in object_list %}
                                <tr>
                                    <th scope="row"></th>
                                    <td>{{ matkul.nama_matkul }}</td>
                                    <td>{{ matkul.semester_tahun }}</td>
                                    <td>{{ matkul.jumlah_sks }}</td>
                                    <td>{{ matkul.nama_dosen }}</td>
                                    <td>{{ matkul.ruang_kuliah }}</td>
                                    <td>{{ matkul.deskripsi }}</td>
                                    <td>
                                        <a class="btn btn-outline-danger" value="Delete" href="{% url 'schedule:delete' matkul.id %}">Remove</a>   
                                    </td>
                                </tr>
                            {% endfor %}
                           
                    </tbody>
                </table>
            </div>

            </div>
        </div>
    </div>
</div>
{% endblock content %}

search/templates/search/search.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>My Schedule</title>
{% endblock meta %} {% block content %}
<div class="container-fluid ">
    <!-- Content here -->

    <div class="place atas">
            <div class="input-group mb-3">
                <input type="text" class="form-control" placeholder="Masukan judul buku" id="cari">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="submit" id="button-cari">Search</button>
                </div>
            </div>
    </div>

    <div class="place hasil">
        <div class="kepala">
            <h2>Hasil Pencarian</h2>
        </div>
        <div class="pencarian">
            
        </div>
    </div>

</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/loader.js" %}"></script>
    <script src="{% static "js/jquery.js" %}"></script>
    <link rel="icon" href="https://lh3.googleusercontent.com/5sDBb4bZq6FJZ6tDWLxJPcJN5V_02GLgZ5D9QPyiDMA8HRCCGNzcPnyzvexAq11bTATwMbTgdVnlOgt9u1kpiyIXTl3UM3c9EQN-LbWY-xiUaZXUq3y8wHozTUFlCKScycOVnjVDDA=s260-p-k">
    {% block meta %} {% endblock meta %}
</head>

<body>
    <div id="loader-wrapper">
    <div id="loader"></div>
 
    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>
 
    </div>
    <nav class="nav navbar fixed-top navbar-expand-lg navbar-dark">
        <a class="navbar-brand" href="#">Y02</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link {% if nbar == 'home' %}active{% endif %}" href="{% url 'main:home'%}">Home</a>
                </li>
                <li class=" nav-item ">
                    <a class="nav-link {% if nbar == 'activities' %}active{% endif %}" href="{% url 'activities:activities'%}">Activities</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link {% if nbar == 'project' %}active{% endif %}" href="{% url 'project:project'%}">Project</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link {% if nbar == 'search' %}active{% endif %}" href="{% url 'search:search'%}">Search</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link {% if nbar == 'schedule' %}active{% endif %}" href="{% url 'schedule:schedule'%}">My Schedule</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="nav-item dropdown">
                {% if user.is_authenticated %}
                    <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Hello {{user.get_username}}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        
                        <a class="dropdown-item" href="{% url 'main:logout' %}">Log out</a>
                    </div>
                {% else %}
                    <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Hello Guest
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'main:login' %}">Log in</a>
                        <a class="dropdown-item" href="{% url 'main:signup' %}">Sign in</a>
                    </div>
                {% endif %}
                </li>
            </ul>
        </div>
    </nav>

    
    <div class="mainbox container-fluid">
        {% block content %} {% endblock content %}

    </div>
    
    <footer class="page-footer">
        <div class="contact row row-cols-4 ">
            <div class="kepala col-12 ">
                <h3>See me on:</h3>
                <p> </p>
            </div>
            <div class="ig col-1 ">
                <a href="https://www.instagram.com/prst_y02/ ">
                    <img src="/static/logo/instagram.png " class="logo " alt=" ">
                </a>
            </div>
            <div class="linkin col-1 ">
                <a href="https://www.linkedin.com/in/yadhit-prasetya-2857b5185 ">
                    <img src="/static/logo/linkedin.png " class="logo " alt=" ">
                </a>
            </div>
            <div class="line col-1 ">
                <a href="https://line.me/ti/p/NE_w8JKFyE ">
                    <img src="/static/logo/line-logo.png " class="logo " alt=" ">
                </a>
            </div>
            <div class="twitter col-1 ">
                <a href="https://twitter.com/nightwalker_02?s=09 ">
                    <img src="/static/logo/twitter.png " href="https://twitter.com/nightwalker_02?s=09 " class="logo " alt=" ">
                </a>
            </div>

        </div>
    </footer>


    {% comment %} <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js " integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj " crossorigin="anonymous "></script> {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js " integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN " crossorigin="anonymous "></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js " integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV " crossorigin="anonymous "></script>
</body>

</html>